# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: spider

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Spider
      working-directory: embedded
      run: |
        python embedded.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name     "qitas"
        git config --global user.email    ${{ secrets.COMMIT_EMAIL }}
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
